name: Fetch & merge the stats 
on:
  #schedule: 
  #- cron: "30 4 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        git config --global user.name paulcarroty && git config --global user.email $GMAIL
        hub release delete nightly
        node index.js
        hub release create -m "Nightly build `date -u`" -a daily.json -a weekly.json -a monthly.json -a yearly.json nightly
      env: 
        GITHUB_TOKEN: ${{ secrets.GT }}
        GMAIL: ${{ secrets.GMAIL }}

